# Generated by Django 2.2.7 on 2019-11-10 21:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_auto_20191110_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='biography',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Biografia'),
        ),
    ]
