# Generated by Django 2.2.7 on 2019-11-11 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0003_auto_20191110_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='development_stack',
            field=models.CharField(max_length=50, null=True, verbose_name='tecnologias'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='job_title',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Este campo no puede contener numeros', regex='^([A-Za-zÀ-ÖØ-öø-ÿ\\s]*)$')], verbose_name='titulo'),
        ),
    ]
