# Generated by Django 2.2.7 on 2019-11-11 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191110_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactspeaker',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Este campo no puede contener numeros', regex='^([A-Za-zÀ-ÖØ-öø-ÿ\\s]*)$')], verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='contactspeaker',
            name='job_title',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Este campo no puede contener numeros', regex='^([A-Za-zÀ-ÖØ-öø-ÿ\\s]*)$')], verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='contactspeaker',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Este campo no puede contener numeros', regex='^([A-Za-zÀ-ÖØ-öø-ÿ\\s]*)$')], verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='contactspeaker',
            name='message',
            field=models.TextField(max_length=256, verbose_name='mensaje'),
        ),
    ]
