# Generated by Django 2.2.7 on 2019-11-11 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Este campo no puede contener numeros', regex='^([A-Za-zÀ-ÖØ-öø-ÿ\\s]*)$')], verbose_name='Título'),
        ),
    ]
