# Generated by Django 2.2.7 on 2019-11-10 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speakers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Titulo')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtitulo')),
                ('content', models.TextField(max_length=200, verbose_name='Contenido')),
                ('picture', models.ImageField(upload_to='blogs', verbose_name='imagen del post')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speakers.Speaker', verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'blogs',
            },
        ),
    ]
