# Generated by Django 2.2.7 on 2019-11-11 14:31

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20191110_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=4000, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Este campo no puede contener numeros', regex='^([A-Za-zÀ-ÖØ-öø-ÿ\\s]*)$')], verbose_name='Subtitulo'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Este campo no puede contener numeros', regex='^([A-Za-zÀ-ÖØ-öø-ÿ\\s]*)$')], verbose_name='Titulo'),
        ),
    ]
